# Generated by Django 2.2.2 on 2019-09-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('slug', models.SlugField()),
                ('classify', models.CharField(max_length=10, unique=True, verbose_name='分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('details', models.TextField(verbose_name='详情')),
                ('classify', models.CharField(choices=[('product', '产品'), ('service', '服务'), ('equipment', '设备')], max_length=10, verbose_name='分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('date', models.DateTimeField(verbose_name='发布时间')),
                ('body', models.TextField(verbose_name='内容')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_delete', models.BooleanField(choices=[(0, '显示'), (1, '隐藏')], default=False, verbose_name='状态')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huichuangbiotech.ClassifyModel', verbose_name='分类')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
