# Generated by Django 2.2.2 on 2019-10-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huichuangbiotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=600)),
                ('pic', models.ImageField(upload_to='upload')),
                ('ctopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huichuangbiotech.CTopic')),
            ],
        ),
    ]
